# 从一个基础镜像centos:6.8开始构建
FROM noveluser/centos6:ssh
# 维护者信息
MAINTAINER from cyy by  "wxp205@cyy928.com"
#添加配置
COPY jdk-8u151-linux-x64.rpm /data/package/
COPY play-1.4.2 /data/package/play-1.4.2/
RUN yum install /data/package/jdk-8u151-linux-x64.rpm -y
RUN rm -f /data/package/jdk-8u151-linux-x64.rpm

# 定义环境变量
ENV PLAY /data/package/play-1.4.2/
ENV PATH $PLAY:$PATH

# 暴露端口

#设置自启动命令
